# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  condition: 

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'AzureSandbox(f645938d-2368-4a99-b589-ea72e5544719)'
    subscriptionId: 'f645938d-2368-4a99-b589-ea72e5544719'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/jaredthivener/Azure-Bicep/blob/main/AKS/main.bicep'
    deploymentMode: 'Incremental'